name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.actor }} is testing the ${{ github.repository }} repository."
      - name: Make get Request
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://jsonplaceholder.typicode.com/todos/1"
          method: GET
      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}
          echo ${{ steps.myRequest.outputs.status }}